# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 4000, host: 4000

  # install dependencies
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install epel-release nodejs httpd gcc make git -y
  SHELL

  config.vm.provision "shell", path: "install_ruby.sh"

  # install jekyll
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install rubygems -y
    gem install jekyll bundler
    git clone https://github.com/mRemoteNG/mRemoteNG.git --branch gh-pages
    bundle install
    bundle exec jekyll serve --drafts --config _config.yaml,_config-dev.yaml
  SHELL

end