# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.box = "opentable/win-2008r2-standard-amd64-nocm"

	config.vm.provider "virtualbox" do |vb|
		vb.gui = true
		vb.memory = "2560"
	end

	config.vm.provision "shell", path: "../SharedScripts/Windows/SystemConfig/disable_uac.ps1"
	config.vm.provision "shell", path: "../SharedScripts/Windows/DotNet/install_dotnet_40.ps1"
	# a restart occurs here
	config.vm.provision "shell", path: "../SharedScripts/Windows/WindowsUpdates/win2008r2_sp1.ps1"

end